// <auto-generated />
namespace Products.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addProducttable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addProducttable));
        
        string IMigrationMetadata.Id
        {
            get { return "202004070001356_addProducttable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
